name: pages

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: install-r
        uses: r-lib/actions/setup-r@v1

      - name: install-pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: install-tex
        uses: r-lib/actions/setup-tinytex@v1

      - name: install-pandoc-citeproc
        run: cabal install pandoc-citeproc

      - name: install-pandoc-include-code
        run: cabal install pandoc-include-code

      - name: install-sassc
        run: |
          cd /usr/local/lib/
          sudo git clone https://github.com/sass/sassc.git --branch 3.4.2 --depth 1
          sudo git clone https://github.com/sass/libsass.git --branch 3.4-stable --depth 1
          sudo git clone https://github.com/sass/sass-spec.git --depth=1
          echo 'SASS_LIBSASS_PATH="/usr/local/lib/libsass"' | sudo tee -a /etc/environment
          source /etc/environment
          sudo make -C libsass
          sudo make -C sassc
          sudo make -C sassc install

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: make build

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: clean-build
        run: |
          cd build
          rm -rf cache
          rm -rf index_files
          rm -rf tmp

      - name: deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_PAT: ${{secrets.GITHUB_PAT}}
